config/routes.rb
Beatbot::Application.routes.draw do
  resources :playlists

  resources :searches

  resources :songs

  match 'text_to_playlist' => "searches#new"

  root :to => 'home#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  attr_accessor :playlist_url
  has_many :songs
  accepts_nested_attributes_for :songs

  def create_playlist(songs)
  	self.playlist_url = "http://www.google.com"
  end

  def self.as_json_options(options={})
    options ||= {}
    options[:methods] ||= []
    options[:methods].concat [:playlist_url]
    options
  end

  def as_json(options={})
    super(Playlist.as_json_options)
  end
end

app/models/search.rb
class Search < ActiveRecord::Base

 	def self.get_video_url(search_term)
		search_term.gsub!(' ','+')
		search_term.gsub!('\'','%27')
		base_url = "https://gdata.youtube.com/feeds/api/videos?v=2&alt=jsonc&q="
		url = base_url + search_term + "&start-index=1&max-results=10"
		return url
	end

	def self.get_search_results(url_to_search)
		curl = Curl::Easy.new(url_to_search)
		curl.perform
		res_str = curl.body_str

		final_arr = []

		r = JSON.parse(res_str, :quirks_mode => true)
		r['data']['items'].each do |x|
			final_arr << {:id => x['id'], :name => x['title'], :url => "http://www.youtube.com/watch?v="+x['id']} 
		end
		final_arr
	end

	def self.get_suggestions(query)
		url_to_search = self.get_video_url(query)
		self.get_search_results(url_to_search)
 	end 
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :genre, :name, :song_id, :playlist_id
  belongs_to :playlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :authenticate_user!

  def index
    
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new()
    @playlist.create_playlist(params[:playlist])
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
  <!-- slider -->
  <div class="container demo-2" style="margin-top:5px;">
  	<div id="slider" class="sl-slider-wrapper">

			<div class="sl-slider">
				
				  <div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
						<div class="sl-slide-inner">
							<div class="bg-img bg-img-1"></div>
							<h2>
								<ul class="six columns" style="margin: 0 auto;">
									<li>
										<i class="icon-doc-text"></i>
										<i class="icon-right-thin"></i>
										<i class="icon-music"></i>
									</li>
								</ul>
							</h2>
							<br>
							<blockquote><p>Ever wanted to listen to the same songs your friends are listening to and been lazy to search for them yourself? We got you covered.. Just enter keywords of each song (song title or a sentence in the song), sit back and enjoy</p></blockquote>
							<div class="medium primary btn"><a href="#">Try it now</a></div>
						</div>
					</div>
					
					<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
						<div class="sl-slide-inner">
							<div class="bg-img bg-img-2"></div>
							<h2>
								<ul class="six columns" style="margin: 0 auto;">
									<li>
										<i class="icon-location"></i>
										<i class="icon-right-thin"></i>
										<i class="icon-music"></i>
									</li>
								</ul>
							</h2>
							<br>
							<blockquote><p>Until he extends the circle of his compassion to all living things, man will not himself find peace.</p><cite>Albert Schweitzer</cite></blockquote>
						</div>
					</div>
					
					<div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
						<div class="sl-slide-inner">
							<div class="bg-img bg-img-3"></div>
							<h2>
								<ul class="six columns" style="margin: 0 auto;">
									<li>
										:)
										<i class="icon-right-thin"></i>
										<i class="icon-music"></i>
									</li>
								</ul>
							</h2>
							<br>
							<blockquote><p>Thousands of people who say they 'love' animals sit down once or twice a day to enjoy the flesh of creatures who have been utterly deprived of everything that could make their lives worth living and who endured the awful suffering and the terror of the abattoirs.</p><cite>Dame Jane Morris Goodall</cite></blockquote>
						</div>
					</div>

					<div class="sl-slide" data-orientation="vertical" data-slice1-rotation="-5" data-slice2-rotation="25" data-slice1-scale="2" data-slice2-scale="1">
						<div class="sl-slide-inner">
							<div class="bg-img bg-img-4"></div>
							<h2>
								<ul class="six columns" style="margin: 0 auto;">
									<li>
										<i class="icon-download"></i>
									</li>
								</ul>
							</h2>
							
						</div>
					</div>
				</div><!-- /sl-slider -->

				<nav id="nav-dots" class="nav-dots">
					<span class="nav-dot-current"></span>
					<span></span>
					<span></span>
					<span></span>
				</nav>

			</div><!-- /slider-wrapper -->
	</div>
  <!-- slider end -->
<script type="text/javascript">	
	$(function() {
	
		var Page = (function() {

			var $nav = $( '#nav-dots > span' ),
				slitslider = $( '#slider' ).slitslider( {
					onBeforeChange : function( slide, pos ) {

						$nav.removeClass( 'nav-dot-current' );
						$nav.eq( pos ).addClass( 'nav-dot-current' );

					}
				} ),

				init = function() {

					initEvents();
					
				},
				initEvents = function() {

					$nav.each( function( i ) {
					
						$( this ).on( 'click', function( event ) {
							
							var $dot = $( this );
							
							if( !slitslider.isActive() ) {

								$nav.removeClass( 'nav-dot-current' );
								$dot.addClass( 'nav-dot-current' );
							
							}
							
							slitslider.jump( i + 1 );
							return false;
						
						} );
						
					} );

				};

				return { init : init };

		})();

		Page.init();

		/**
		 * Notes: 
		 * 
		 * example how to add items:
		 */

		/*
		
		var $items  = $('<div class="sl-slide sl-slide-color-2" data-orientation="horizontal" data-slice1-rotation="-5" data-slice2-rotation="10" data-slice1-scale="2" data-slice2-scale="1"><div class="sl-slide-inner bg-1"><div class="sl-deco" data-icon="t"></div><h2>some text</h2><blockquote><p>bla bla</p><cite>Margi Clarke</cite></blockquote></div></div>');
		
		// call the plugin's add method
		ss.add($items);

		*/
	
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beatbot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :modernizr %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="beatbot-navbar navbar" id="nav1">
	  <div class="row">
	    
	    <h4 class="four columns logo" style="margin-left:400px;">
	      <a href="/">
	        <!-- <img src="img/gumby_mainlogo.png" gumby-retina /> -->
	        BeatBot
	      </a>
	    </h4>
	    <!-- <ul class="eight columns" style="float:right;">
				<li class="three columns"><a href=""><i class="icon-music"></i>Features</a></li>
				<li class="three columns"><a href=""><i class="icon-download"></i> Download</a> </li>
				<li class="three columns"><a href=""><i class="icon-info-circled"></i> About</a> </li>
			</ul> -->
	  </div>
	</div>
	  
	 <div id="beatbot_content">
	 </div>
	 <%= yield %>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.name %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @playlist.name %>
</p>


<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!--
  <li class="append field">
    <div class="field">
      <%= f.label :songs %><br />
      <%= f.text_field :songs, :class => "text input" %>
    </div>
    <div class="actions medium secondary btn">
      <%= f.submit :value => "Create playlist" %>
    </div>
  </li>
-->
  <li class="append field">
    <%= f.text_field :songs, :class => "text input" %>
    <div class="medium secondary btn"><%= f.submit :value => "Create playlist" %></div>
  </li>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Songs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.songs %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<script type="text/javascript">    
  window.router = new BeatBot.Routers.ApplicationRouter();
  Backbone.history.start({pushState: true, hashChange: false});
</script>

<script type="text/javascript">

	var params = { allowScriptAccess: "always" };
	swfobject.embedSWF("http://www.youtube.com/v/3vC5TsSyNjU?enablejsapi=1&playerapiid=ytplayer&version=3", "ytplayer", "1300", "600", "8", null, null, params);

	function onYouTubePlayerReady(playerId) {
    ytplayer = document.getElementById("ytplayer");
    window.router.view.current_url = "http://www.youtube.com/v/SuHmEo0Bx7Q"
    ytplayer.addEventListener("onStateChange", "onytplayerStateChange");
  }
  function onytplayerStateChange(newState){
  	window.router.view.go_to_next_video(newState)
  }

</script>
  

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Songs:</b>
  <%= @search.songs %>
</p>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.text_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Song</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= song.song_id %></td>
    <td><%= song.genre %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Song:</b>
  <%= @song.song_id %>
</p>

<p>
  <b>Genre:</b>
  <%= @song.genre %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>